# Generated by Django 4.1.1 on 2022-12-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityLocation',
            field=models.CharField(default='IT224', max_length=100),
            preserve_default=False,
        ),
    ]
