# Generated by Django 4.1.1 on 2022-12-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_activitylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userBio',
            field=models.CharField(default='Hello this is my defualt bio coz the developer forget to add this field earlier', max_length=100),
            preserve_default=False,
        ),
    ]
